---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dev
patches:
  - target:
      kind: HelmRelease
      name: kubeping
    patch: |
      - op: replace
        path: /spec/values/web/ingress/host
        value: kubeping.dev-cluster.example.az
