---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../dev
patches:
  - target:
      kind: HelmRelease
      name: app22
    patch: |
      - op: replace
        path: /spec/values/ingress/hosts/0/host
        value: app22-dev.example.az
      - op: replace
        path: /spec/values/ingress/tls/0/hosts/0
        value: app22-dev.example.az
