---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
  interval: 5m
  chart:
    spec:
      chart: traefik
      version: "35.x"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true
    service:
      type: LoadBalancer
