---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: HelmRelease
      name: app22
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
      - op: add
        path: /spec/values/env/LOG_LEVEL
        value: info
